'use client';

import { ToolProcessor } from '@/types/tool';

// Each entry is a thunk that dynamic-imports exactly one processor module.
// Next.js/Turbopack splits each import() into its own chunk so heavy deps
// (sql-formatter, js-yaml) are only fetched when the matching tool page loads.
const processorLoaders: Record<string, () => Promise<ToolProcessor>> = {
  'json-formatter':           () => import('./json-formatter').then(m => m.jsonFormatterProcessor),
  'json-validator':           () => import('./json-validator').then(m => m.jsonValidatorProcessor),
  'json-minifier':            () => import('./json-minifier').then(m => m.jsonMinifierProcessor),
  'json-diff':                () => import('./json-diff').then(m => m.jsonDiffProcessor),
  'base64-encoder':           () => import('./base64-encoder').then(m => m.base64EncoderProcessor),
  'base64-decoder':           () => import('./base64-decoder').then(m => m.base64DecoderProcessor),
  'url-encoder':              () => import('./url-encoder').then(m => m.urlEncoderProcessor),
  'url-decoder':              () => import('./url-decoder').then(m => m.urlDecoderProcessor),
  'html-encoder':             () => import('./html-encoder').then(m => m.htmlEncoderProcessor),
  'html-decoder':             () => import('./html-decoder').then(m => m.htmlDecoderProcessor),
  'jwt-decoder':              () => import('./jwt-decoder').then(m => m.jwtDecoderProcessor),
  'uuid-generator':           () => import('./uuid-generator').then(m => m.uuidGeneratorProcessor),
  'uuid-validator':           () => import('./uuid-validator').then(m => m.uuidValidatorProcessor),
  'password-generator':       () => import('./password-generator').then(m => m.passwordGeneratorProcessor),
  'unix-timestamp-converter': () => import('./unix-timestamp-converter').then(m => m.unixTimestampConverterProcessor),
  'timestamp-to-date':        () => import('./timestamp-to-date').then(m => m.timestampToDateProcessor),
  'regex-tester':             () => import('./regex-tester').then(m => m.regexTesterProcessor),
  'sql-formatter':            () => import('./sql-formatter').then(m => m.sqlFormatterProcessor),
  'xml-formatter':            () => import('./xml-formatter').then(m => m.xmlFormatterProcessor),
  'yaml-formatter':           () => import('./yaml-formatter').then(m => m.yamlFormatterProcessor),
  'yaml-to-json':             () => import('./yaml-to-json').then(m => m.yamlToJsonProcessor),
  'json-to-csv':              () => import('./json-to-csv').then(m => m.jsonToCsvProcessor),
  'csv-to-json':              () => import('./csv-to-json').then(m => m.csvToJsonProcessor),
  'json-to-yaml':             () => import('./json-to-yaml').then(m => m.jsonToYamlProcessor),
  'json-to-xml':              () => import('./json-to-xml').then(m => m.jsonToXmlProcessor),
  'hash-generator':           () => import('./hash-generator').then(m => m.hashGeneratorProcessor),
  'html-formatter':           () => import('./html-formatter').then(m => m.htmlFormatterProcessor),
  'css-formatter':            () => import('./css-formatter').then(m => m.cssFormatterProcessor),
  'diff-checker':             () => import('./diff-checker').then(m => m.diffCheckerProcessor),
  'markdown-preview':         () => import('./markdown-preview').then(m => m.markdownPreviewProcessor),
  'word-counter':             () => import('./word-counter').then(m => m.wordCounterProcessor),
  'color-picker':             () => import('./color-picker').then(m => m.colorPickerProcessor),
  'jsonpath-tester':          () => import('./jsonpath-tester').then(m => m.jsonpathTesterProcessor),
  'json-schema-validator':    () => import('./json-schema-validator').then(m => m.jsonSchemaValidatorProcessor),
  'json-escape':              () => import('./json-escape').then(m => m.jsonEscapeProcessor),
  'json-sorter':              () => import('./json-sorter').then(m => m.jsonSorterProcessor),
  'json-repair':             () => import('./json-repair').then(m => m.jsonRepairProcessor),
  'json-flatten':            () => import('./json-flatten').then(m => m.jsonFlattenProcessor),
  'json-size-analyzer':      () => import('./json-size-analyzer').then(m => m.jsonSizeAnalyzerProcessor),
  'json-search':             () => import('./json-search').then(m => m.jsonSearchProcessor),
  'json-stringify':          () => import('./json-stringify').then(m => m.jsonStringifyProcessor),
  'json-token-counter':      () => import('./json-token-counter').then(m => m.jsonTokenCounterProcessor),
  'jsonc-to-json':           () => import('./jsonc-to-json').then(m => m.jsoncToJsonProcessor),
  'json-to-sql':             () => import('./json-to-sql').then(m => m.jsonToSqlProcessor),
  'json-to-markdown':        () => import('./json-to-markdown').then(m => m.jsonToMarkdownProcessor),
  'json-schema-generator':   () => import('./json-schema-generator').then(m => m.jsonSchemaGeneratorProcessor),
  'json-table-viewer':       () => import('./json-table-viewer').then(m => m.jsonTableViewerProcessor),
  'json-to-typescript':      () => import('./json-to-typescript').then(m => m.jsonToTypescriptProcessor),
  'json-to-python':          () => import('./json-to-python').then(m => m.jsonToPythonProcessor),
  'json-to-csharp':          () => import('./json-to-csharp').then(m => m.jsonToCsharpProcessor),
  'json-to-go':              () => import('./json-to-go').then(m => m.jsonToGoProcessor),
  'json-to-kotlin':          () => import('./json-to-kotlin').then(m => m.jsonToKotlinProcessor),
  'json-to-swift':           () => import('./json-to-swift').then(m => m.jsonToSwiftProcessor),
  'json-to-rust':            () => import('./json-to-rust').then(m => m.jsonToRustProcessor),
  'json-to-php':             () => import('./json-to-php').then(m => m.jsonToPhpProcessor),
  'csv-formatter':            () => import('./csv-formatter').then(m => m.csvFormatterProcessor),
  'csv-validator':            () => import('./csv-validator').then(m => m.csvValidatorProcessor),
  'xml-validator':            () => import('./xml-validator').then(m => m.xmlValidatorProcessor),
  'xml-minifier':             () => import('./xml-minifier').then(m => m.xmlMinifierProcessor),
  'xml-to-json':              () => import('./xml-to-json').then(m => m.xmlToJsonProcessor),
  'xml-escape':               () => import('./xml-escape').then(m => m.xmlEscapeProcessor),
  'yaml-validator':           () => import('./yaml-validator').then(m => m.yamlValidatorProcessor),
  'yaml-minifier':            () => import('./yaml-minifier').then(m => m.yamlMinifierProcessor),
  'text-case-converter':      () => import('./text-case-converter').then(m => m.textCaseConverterProcessor),
  'remove-duplicate-lines':   () => import('./remove-duplicate-lines').then(m => m.removeDuplicateLinesProcessor),
  'sort-lines':               () => import('./sort-lines').then(m => m.sortLinesProcessor),
  'age-calculator':           () => import('./age-calculator').then(m => m.ageCalculatorProcessor),
  'date-difference-calculator': () => import('./date-difference-calculator').then(m => m.dateDifferenceCalculatorProcessor),
  'days-between-dates':       () => import('./days-between-dates').then(m => m.daysBetweenDatesProcessor),
  'business-days-calculator': () => import('./business-days-calculator').then(m => m.businessDaysCalculatorProcessor),
  'add-subtract-date':        () => import('./add-subtract-date').then(m => m.addSubtractDateProcessor),
  'time-duration-calculator': () => import('./time-duration-calculator').then(m => m.timeDurationCalculatorProcessor),
  'countdown-timer':          () => import('./countdown-timer').then(m => m.countdownTimerProcessor),
  'days-until':               () => import('./days-until').then(m => m.daysUntilProcessor),
  'week-number-calculator':   () => import('./week-number-calculator').then(m => m.weekNumberCalculatorProcessor),
  'leap-year-calculator':     () => import('./leap-year-calculator').then(m => m.leapYearCalculatorProcessor),
  'date-to-unix-timestamp':   () => import('./date-to-unix-timestamp').then(m => m.dateToUnixTimestampProcessor),
  'unix-timestamp-to-date':   () => import('./unix-timestamp-to-date').then(m => m.unixTimestampToDateProcessor),
  'iso-8601-converter':       () => import('./iso-8601-converter').then(m => m.iso8601ConverterProcessor),
  'date-format-converter':    () => import('./date-format-converter').then(m => m.dateFormatConverterProcessor),
  'timezone-converter':       () => import('./timezone-converter').then(m => m.timezoneConverterProcessor),
  'utc-converter':            () => import('./utc-converter').then(m => m.utcConverterProcessor),
  'world-clock':              () => import('./world-clock').then(m => m.worldClockProcessor),
  'meeting-time-planner':     () => import('./meeting-time-planner').then(m => m.meetingTimePlannerProcessor),
  'cron-generator':           () => import('./cron-generator').then(m => m.cronGeneratorProcessor),
  'cron-parser':              () => import('./cron-parser').then(m => m.cronParserProcessor),
};

export async function getProcessor(toolId: string): Promise<ToolProcessor | undefined> {
  const loader = processorLoaders[toolId];
  if (!loader) return undefined;
  return loader();
}
