import { ToolProcessor, ToolInput, ToolResult } from '@/types/tool';

// ---------------------------------------------------------------------------
// Type inference
// ---------------------------------------------------------------------------

interface InterfaceNode {
  name: string;
  fields: FieldDef[];
}

interface FieldDef {
  key: string;
  tsType: string;
  optional: boolean;
}

// Track generated interfaces to avoid duplicates and collect nested ones.
type InterfaceMap = Map<string, InterfaceNode>;

function sanitizeIdentifier(name: string): string {
  // Replace leading digits and invalid chars, then PascalCase the segments.
  const cleaned = name.replace(/[^a-zA-Z0-9_$]/g, '_').replace(/^([0-9])/, '_$1');
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

function buildInterfaceName(parentName: string, key: string): string {
  return sanitizeIdentifier(parentName) + sanitizeIdentifier(key);
}

/**
 * Infer the TypeScript type string for a JSON value.
 * Nested objects cause new named interfaces to be registered in `ifaceMap`.
 */
function inferTsType(
  value: unknown,
  fieldName: string,
  parentInterfaceName: string,
  ifaceMap: InterfaceMap,
): string {
  if (value === null) return 'null';
  if (typeof value === 'boolean') return 'boolean';
  if (typeof value === 'number') return 'number';
  if (typeof value === 'string') return 'string';

  if (Array.isArray(value)) {
    if (value.length === 0) return 'unknown[]';
    // Infer type from first element
    const elemType = inferTsType(value[0], fieldName + 'Item', parentInterfaceName, ifaceMap);
    return `${elemType}[]`;
  }

  if (typeof value === 'object') {
    const obj = value as Record<string, unknown>;
    const ifaceName = buildInterfaceName(parentInterfaceName, fieldName);
    buildInterface(obj, ifaceName, ifaceMap);
    return ifaceName;
  }

  return 'unknown';
}

function buildInterface(
  obj: Record<string, unknown>,
  ifaceName: string,
  ifaceMap: InterfaceMap,
): void {
  // Avoid rebuilding if already registered
  if (ifaceMap.has(ifaceName)) return;

  const fields: FieldDef[] = [];

  for (const [key, val] of Object.entries(obj)) {
    const tsType = inferTsType(val, key, ifaceName, ifaceMap);
    fields.push({ key, tsType, optional: false });
  }

  ifaceMap.set(ifaceName, { name: ifaceName, fields });
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

function renderInterface(
  node: InterfaceNode,
  optionalFields: boolean,
  useExportKeyword: boolean,
  useInterface: boolean,
): string {
  const exportKw = useExportKeyword ? 'export ' : '';
  const fields = node.fields.map((f) => {
    const optMark = optionalFields ? '?' : '';
    // Quote keys that are not valid identifiers
    const needsQuote = !/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(f.key);
    const keyStr = needsQuote ? `"${f.key}"` : f.key;
    return `  ${keyStr}${optMark}: ${f.tsType};`;
  });

  if (useInterface) {
    return [
      `${exportKw}interface ${node.name} {`,
      ...fields,
      `}`,
    ].join('\n');
  } else {
    // type alias
    return [
      `${exportKw}type ${node.name} = {`,
      ...fields,
      `};`,
    ].join('\n');
  }
}

function generateTypeScript(
  parsed: unknown,
  useInterface: boolean,
  optionalFields: boolean,
  useExportKeyword: boolean,
): string {
  const ifaceMap: InterfaceMap = new Map();

  const lines: string[] = [
    '// Generated by DevToolsHub — https://devtoolshub.dev',
    '',
  ];

  let rootType: string;

  if (parsed === null || typeof parsed !== 'object') {
    // Scalar root — just emit a type alias
    const scalarType =
      typeof parsed === 'string'
        ? 'string'
        : typeof parsed === 'number'
          ? 'number'
          : typeof parsed === 'boolean'
            ? 'boolean'
            : 'null';
    const exportKw = useExportKeyword ? 'export ' : '';
    const kwStr = useInterface ? 'type' : 'type';
    lines.push(`${exportKw}${kwStr} RootObject = ${scalarType};`);
    return lines.join('\n');
  }

  if (Array.isArray(parsed)) {
    rootType = 'array';
    // Treat array items as the root object if they are objects
    if (parsed.length > 0 && typeof parsed[0] === 'object' && parsed[0] !== null && !Array.isArray(parsed[0])) {
      buildInterface(parsed[0] as Record<string, unknown>, 'RootObject', ifaceMap);
    }
    // Render nested interfaces (deepest first), then root
    const nestedNames = Array.from(ifaceMap.keys()).filter((n) => n !== 'RootObject');
    for (const name of nestedNames) {
      const node = ifaceMap.get(name)!;
      lines.push(renderInterface(node, optionalFields, useExportKeyword, useInterface));
      lines.push('');
    }
    const rootNode = ifaceMap.get('RootObject');
    if (rootNode) {
      lines.push(renderInterface(rootNode, optionalFields, useExportKeyword, useInterface));
      lines.push('');
    }
    const exportKw = useExportKeyword ? 'export ' : '';
    lines.push(`${exportKw}type RootArray = RootObject[];`);
  } else {
    rootType = 'object';
    buildInterface(parsed as Record<string, unknown>, 'RootObject', ifaceMap);
    // Render nested interfaces (non-root first), then RootObject last
    const nestedNames = Array.from(ifaceMap.keys()).filter((n) => n !== 'RootObject');
    for (const name of nestedNames) {
      const node = ifaceMap.get(name)!;
      lines.push(renderInterface(node, optionalFields, useExportKeyword, useInterface));
      lines.push('');
    }
    const rootNode = ifaceMap.get('RootObject');
    if (rootNode) {
      lines.push(renderInterface(rootNode, optionalFields, useExportKeyword, useInterface));
    }
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Option helpers
// ---------------------------------------------------------------------------

function getUseInterface(options?: Record<string, unknown>): boolean {
  return options?.useInterface !== false;
}

function getOptionalFields(options?: Record<string, unknown>): boolean {
  return options?.optionalFields === true;
}

function getExportKeyword(options?: Record<string, unknown>): boolean {
  return options?.exportKeyword !== false;
}

// ---------------------------------------------------------------------------
// Meta helpers
// ---------------------------------------------------------------------------

function countTopLevelProps(value: unknown): number {
  if (value === null || typeof value !== 'object') return 0;
  if (Array.isArray(value)) {
    if (value.length > 0 && typeof value[0] === 'object' && value[0] !== null && !Array.isArray(value[0])) {
      return Object.keys(value[0] as Record<string, unknown>).length;
    }
    return 0;
  }
  return Object.keys(value as Record<string, unknown>).length;
}

function countNestedInterfaces(ifaceMap: InterfaceMap): number {
  return Math.max(0, ifaceMap.size - 1);
}

// ---------------------------------------------------------------------------
// Processor
// ---------------------------------------------------------------------------

const EXAMPLE_INPUT = JSON.stringify(
  {
    id: 1,
    name: 'Alice',
    active: true,
    score: 9.5,
    address: {
      street: '123 Main St',
      city: 'Springfield',
      zip: '62701',
    },
    tags: ['admin', 'editor'],
  },
  null,
  2,
);

export const jsonToTypescriptProcessor: ToolProcessor = {
  inputLabel: 'JSON Input',
  inputPlaceholder: 'Paste a JSON object or array to generate TypeScript interfaces…',
  autoProcess: false,
  exampleInput: EXAMPLE_INPUT,

  optionControls: [
    {
      key: 'useInterface',
      type: 'checkbox',
      label: 'Use interface (unchecked = type alias)',
      defaultValue: true,
    },
    {
      key: 'exportKeyword',
      type: 'checkbox',
      label: 'Add export keyword',
      defaultValue: true,
    },
    {
      key: 'optionalFields',
      type: 'checkbox',
      label: 'Mark all fields optional (?)',
      defaultValue: false,
    },
  ],

  process(input: ToolInput): ToolResult {
    const raw = input.value.trim();
    if (!raw) return { error: 'Paste a JSON object or array to generate TypeScript types.' };

    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { error: `Invalid JSON: ${msg}` };
    }

    const useInterface = getUseInterface(input.options);
    const optionalFields = getOptionalFields(input.options);
    const exportKeyword = getExportKeyword(input.options);

    const code = generateTypeScript(parsed, useInterface, optionalFields, exportKeyword);

    // Build meta info
    const isArray = Array.isArray(parsed);
    const rootTypeLabel = isArray ? 'array' : parsed === null ? 'null' : typeof parsed;

    // Re-build interface map just for counting (cheap)
    const ifaceMapForMeta: InterfaceMap = new Map();
    if (!isArray && parsed !== null && typeof parsed === 'object') {
      buildInterface(parsed as Record<string, unknown>, 'RootObject', ifaceMapForMeta);
    } else if (isArray && (parsed as unknown[]).length > 0) {
      const first = (parsed as unknown[])[0];
      if (first !== null && typeof first === 'object' && !Array.isArray(first)) {
        buildInterface(first as Record<string, unknown>, 'RootObject', ifaceMapForMeta);
      }
    }

    const topProps = countTopLevelProps(parsed);
    const nestedCount = countNestedInterfaces(ifaceMapForMeta);

    return {
      output: {
        value: code,
        type: 'text',
        label: 'TypeScript Types',
        copyable: true,
        downloadFilename: 'types.ts',
        downloadMime: 'text/plain',
      },
      meta: {
        'root type': rootTypeLabel,
        'properties found': topProps,
        'nested types': nestedCount,
      },
    };
  },
};
