import { ToolProcessor, ToolInput, ToolResult } from '@/types/tool';

// ---------------------------------------------------------------------------
// Kotlin type inference
// ---------------------------------------------------------------------------

type KotlinType =
  | 'String'
  | 'Int'
  | 'Long'
  | 'Double'
  | 'Boolean'
  | 'Any'
  | string; // List<T> or nested data class name

interface KotlinField {
  name: string;
  type: KotlinType;
  nullable: boolean;
}

interface KotlinClass {
  name: string;
  fields: KotlinField[];
}

function toCamelCase(key: string): string {
  // Convert snake_case, kebab-case, PascalCase, or space-separated to camelCase
  return key
    .replace(/[-_\s]+(.)/g, (_, ch: string) => ch.toUpperCase())
    .replace(/^(.)/, (_, ch: string) => ch.toLowerCase());
}

function toPascalCase(key: string): string {
  const cc = toCamelCase(key);
  return cc.charAt(0).toUpperCase() + cc.slice(1);
}

// Sanitize an identifier to be a valid Kotlin name
function sanitizeIdentifier(name: string): string {
  // Replace non-alphanumeric chars with underscore, ensure it starts with a letter
  let safe = name.replace(/[^a-zA-Z0-9_]/g, '_');
  if (/^[0-9]/.test(safe)) safe = '_' + safe;
  return safe || '_field';
}

function inferKotlinType(
  value: unknown,
  key: string,
  classes: Map<string, KotlinClass>,
  nullable: boolean,
): KotlinType {
  if (value === null || value === undefined) return 'Any';

  if (typeof value === 'boolean') return 'Boolean';

  if (typeof value === 'number') {
    if (!Number.isFinite(value)) return 'Double';
    if (Number.isInteger(value)) {
      // Use Long for values outside Int range
      if (value > 2147483647 || value < -2147483648) return 'Long';
      return 'Int';
    }
    return 'Double';
  }

  if (typeof value === 'string') return 'String';

  if (Array.isArray(value)) {
    if (value.length === 0) return 'List<Any>';
    const elementType = inferKotlinType(value[0], key, classes, nullable);
    return `List<${elementType}>`;
  }

  if (typeof value === 'object' && value !== null) {
    // Generate a nested data class
    const className = toPascalCase(sanitizeIdentifier(key));
    collectClasses(value as Record<string, unknown>, className, classes, nullable);
    return className;
  }

  return 'Any';
}

function collectClasses(
  obj: Record<string, unknown>,
  className: string,
  classes: Map<string, KotlinClass>,
  forceNullable: boolean,
): void {
  if (classes.has(className)) return;

  const fields: KotlinField[] = [];

  for (const [key, value] of Object.entries(obj)) {
    const fieldName = toCamelCase(sanitizeIdentifier(key));
    const isNull = forceNullable || value === null || value === undefined;
    const type = inferKotlinType(value, key, classes, forceNullable);
    fields.push({ name: fieldName, type, nullable: isNull });
  }

  // Register before recursing to handle self-referential structures
  classes.set(className, { name: className, fields });
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

function renderDataClass(cls: KotlinClass, serializable: boolean): string {
  const lines: string[] = [];

  if (serializable) {
    lines.push('@Serializable');
  }

  lines.push(`data class ${cls.name}(`);

  cls.fields.forEach((field, idx) => {
    const nullable = field.nullable ? '?' : '';
    const nullDefault = field.nullable ? ' = null' : '';
    const comma = idx < cls.fields.length - 1 ? ',' : '';
    lines.push(`    val ${field.name}: ${field.type}${nullable}${nullDefault}${comma}`);
  });

  lines.push(')');

  return lines.join('\n');
}

function generateKotlinCode(
  parsed: unknown,
  serializable: boolean,
  nullable: boolean,
): { code: string; rootType: string; classCount: number; propertyCount: number } {
  const classes = new Map<string, KotlinClass>();

  let rootType: string;

  if (Array.isArray(parsed)) {
    rootType = 'array';
    if (parsed.length > 0 && typeof parsed[0] === 'object' && parsed[0] !== null) {
      collectClasses(parsed[0] as Record<string, unknown>, 'Root', classes, nullable);
    }
  } else if (typeof parsed === 'object' && parsed !== null) {
    rootType = 'object';
    collectClasses(parsed as Record<string, unknown>, 'Root', classes, nullable);
  } else {
    rootType = typeof parsed;
  }

  const parts: string[] = [];

  parts.push('// Generated by DevToolsHub — https://devtoolshub.dev');
  parts.push('');

  if (serializable) {
    parts.push('import kotlinx.serialization.*');
    parts.push('import kotlinx.serialization.json.*');
    parts.push('');
  }

  // Render nested classes first (dependency order), Root last
  const classOrder: string[] = [];
  const visited = new Set<string>();

  function visitClass(name: string): void {
    if (visited.has(name)) return;
    visited.add(name);
    const cls = classes.get(name);
    if (!cls) return;
    for (const field of cls.fields) {
      // Unwrap List<T> to T
      const innerType = field.type.replace(/^List<(.+)>$/, '$1');
      if (classes.has(innerType) && innerType !== name) {
        visitClass(innerType);
      }
    }
    classOrder.push(name);
  }

  for (const name of classes.keys()) {
    visitClass(name);
  }

  let propertyCount = 0;

  for (const name of classOrder) {
    const cls = classes.get(name)!;
    propertyCount += cls.fields.length;
    parts.push(renderDataClass(cls, serializable));
    parts.push('');
  }

  // Remove trailing blank line
  while (parts.length > 0 && parts[parts.length - 1] === '') {
    parts.pop();
  }

  return {
    code: parts.join('\n'),
    rootType,
    classCount: classes.size,
    propertyCount,
  };
}

// ---------------------------------------------------------------------------
// Options helpers
// ---------------------------------------------------------------------------

function getSerializable(options?: Record<string, unknown>): boolean {
  return options?.serializable !== false;
}

function getNullable(options?: Record<string, unknown>): boolean {
  return options?.nullable === true;
}

// ---------------------------------------------------------------------------
// Example input
// ---------------------------------------------------------------------------

const EXAMPLE_INPUT = JSON.stringify(
  {
    id: 42,
    name: 'Alice',
    verified: true,
    score: 9.8,
    address: {
      street: '123 Main St',
      city: 'Springfield',
      zip: '62701',
    },
    tags: ['developer', 'open-source'],
  },
  null,
  2,
);

// ---------------------------------------------------------------------------
// Processor
// ---------------------------------------------------------------------------

export const jsonToKotlinProcessor: ToolProcessor = {
  inputLabel: 'JSON Input',
  inputPlaceholder:
    '{"id":1,"name":"Alice","verified":true,"score":9.8,"address":{"city":"Springfield"},"tags":["dev"]}',
  autoProcess: false,
  exampleInput: EXAMPLE_INPUT,

  optionControls: [
    {
      key: 'serializable',
      type: 'checkbox',
      label: 'Add @Serializable (kotlinx.serialization)',
      defaultValue: true,
    },
    {
      key: 'nullable',
      type: 'checkbox',
      label: 'Mark all fields nullable (?)',
      defaultValue: false,
    },
  ],

  process(input: ToolInput): ToolResult {
    const raw = input.value.trim();
    if (!raw) return { error: 'Paste a JSON object or array to generate Kotlin data classes.' };

    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { error: `Invalid JSON: ${msg}` };
    }

    if (typeof parsed !== 'object' || parsed === null) {
      return { error: 'Input must be a JSON object or array.' };
    }

    const serializable = getSerializable(input.options);
    const nullable = getNullable(input.options);

    const { code, rootType, classCount, propertyCount } = generateKotlinCode(
      parsed,
      serializable,
      nullable,
    );

    if (classCount === 0) {
      return { error: 'Could not generate any Kotlin classes — check that the input is a non-empty JSON object or array of objects.' };
    }

    return {
      output: {
        value: code,
        type: 'text',
        label: `Kotlin data class${classCount === 1 ? '' : 'es'} (${classCount} class${classCount === 1 ? '' : 'es'})`,
        copyable: true,
        downloadFilename: 'models.kt',
        downloadMime: 'text/plain',
      },
      meta: {
        'root type': rootType,
        'classes generated': classCount,
        'properties found': propertyCount,
        serializable: serializable ? 'yes' : 'no',
        nullable: nullable ? 'yes' : 'no',
      },
    };
  },
};
