import { ToolProcessor, ToolInput, ToolResult } from '@/types/tool';

// ---------------------------------------------------------------------------
// Go type inference
// ---------------------------------------------------------------------------

type GoType = string;

interface StructDef {
  name: string;
  fields: FieldDef[];
}

interface FieldDef {
  goName: string;
  jsonName: string;
  goType: GoType;
}

function toPascalCase(str: string): string {
  if (!str) return 'Field';
  // Handle snake_case, camelCase, kebab-case
  return str
    .replace(/[-_](.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^(.)/, (_, c: string) => c.toUpperCase());
}

/**
 * Returns a Go type string for a JSON value. When an object is encountered a
 * new struct definition is pushed onto `structs` and its name is returned.
 * `structs` accumulates all nested types in encounter order.
 */
function inferGoType(
  value: unknown,
  keyHint: string,
  structs: StructDef[],
  usePointers: boolean,
): GoType {
  if (value === null || value === undefined) {
    return usePointers ? '*interface{}' : 'interface{}';
  }

  if (typeof value === 'boolean') {
    return usePointers ? '*bool' : 'bool';
  }

  if (typeof value === 'number') {
    if (Number.isInteger(value)) {
      return usePointers ? '*int64' : 'int64';
    }
    return usePointers ? '*float64' : 'float64';
  }

  if (typeof value === 'string') {
    return usePointers ? '*string' : 'string';
  }

  if (Array.isArray(value)) {
    if (value.length === 0) {
      return '[]interface{}';
    }
    // Infer element type from the first element
    const elemType = inferGoType(value[0], keyHint + 'Item', structs, false);
    return `[]${elemType}`;
  }

  if (typeof value === 'object') {
    // Generate a named struct for nested objects
    const structName = toPascalCase(keyHint);
    const obj = value as Record<string, unknown>;
    const fields = buildFields(obj, structName, structs, usePointers);

    // Avoid duplicate struct names — check if we already emitted one with
    // the same name (last-wins is acceptable for the simple case).
    const existing = structs.find((s) => s.name === structName);
    if (!existing) {
      structs.push({ name: structName, fields });
    }

    return structName;
  }

  return 'interface{}';
}

function buildFields(
  obj: Record<string, unknown>,
  _parentName: string,
  structs: StructDef[],
  usePointers: boolean,
): FieldDef[] {
  return Object.entries(obj).map(([key, value]) => {
    const goName = toPascalCase(key);
    const goType = inferGoType(value, goName, structs, usePointers);
    return { goName, jsonName: key, goType };
  });
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

function renderStruct(s: StructDef): string {
  const lines: string[] = [];
  lines.push(`type ${s.name} struct {`);
  for (const f of s.fields) {
    // Align tag on a consistent tab stop — use a single tab for simplicity
    lines.push(`\t${f.goName} ${f.goType} \`json:"${f.jsonName}"\``);
  }
  lines.push('}');
  return lines.join('\n');
}

function generateGoCode(
  parsed: unknown,
  packageName: string,
  usePointers: boolean,
): { code: string; rootType: string; structCount: number; propCount: number } {
  const structs: StructDef[] = [];
  let rootType: string;
  let propCount = 0;

  if (Array.isArray(parsed)) {
    // Use first element to infer item struct
    const elem = parsed.length > 0 ? parsed[0] : {};
    if (elem !== null && typeof elem === 'object' && !Array.isArray(elem)) {
      const obj = elem as Record<string, unknown>;
      propCount = Object.keys(obj).length;
      const fields = buildFields(obj, 'Root', structs, usePointers);
      structs.push({ name: 'Root', fields });
    }
    rootType = '[]Root';
  } else if (parsed !== null && typeof parsed === 'object') {
    const obj = parsed as Record<string, unknown>;
    propCount = Object.keys(obj).length;
    const fields = buildFields(obj, 'Root', structs, usePointers);
    structs.push({ name: 'Root', fields });
    rootType = 'Root';
  } else {
    rootType = inferGoType(parsed, 'Root', structs, usePointers);
  }

  const parts: string[] = [];
  parts.push('// Generated by DevToolsHub — https://devtoolshub.dev');
  parts.push('');
  parts.push(`package ${packageName}`);
  parts.push('');

  // Render structs in reverse order so inner types come first
  const reversed = [...structs].reverse();
  for (const s of reversed) {
    parts.push(renderStruct(s));
    parts.push('');
  }

  const code = parts.join('\n').trimEnd() + '\n';
  return { code, rootType: Array.isArray(parsed) ? 'array' : 'object', structCount: structs.length, propCount };
}

// ---------------------------------------------------------------------------
// Options helpers
// ---------------------------------------------------------------------------

function getPackageName(options?: Record<string, unknown>): string {
  const pkg = options?.packageName;
  if (pkg === 'models' || pkg === 'data') return pkg as string;
  return 'main';
}

function getUsePointers(options?: Record<string, unknown>): boolean {
  return options?.pointerFields === true;
}

// ---------------------------------------------------------------------------
// Example input
// ---------------------------------------------------------------------------

const EXAMPLE_INPUT = JSON.stringify(
  {
    id: 42,
    name: 'Alice',
    active: true,
    score: 9.5,
    address: {
      street: '123 Main St',
      city: 'Springfield',
      zip: '12345',
    },
    tags: ['admin', 'editor'],
  },
  null,
  2,
);

// ---------------------------------------------------------------------------
// Processor
// ---------------------------------------------------------------------------

export const jsonToGoProcessor: ToolProcessor = {
  inputLabel: 'JSON Input',
  inputPlaceholder: '{"id":1,"name":"Alice","active":true}',
  autoProcess: false,
  exampleInput: EXAMPLE_INPUT,

  optionControls: [
    {
      key: 'packageName',
      type: 'select',
      label: 'Package Name',
      defaultValue: 'main',
      options: [
        { value: 'main', label: 'main' },
        { value: 'models', label: 'models' },
        { value: 'data', label: 'data' },
      ],
    },
    {
      key: 'pointerFields',
      type: 'checkbox',
      label: 'Pointer fields (nullable)',
      defaultValue: false,
    },
  ],

  process(input: ToolInput): ToolResult {
    const raw = input.value.trim();
    if (!raw) return { error: 'Paste JSON to generate Go structs.' };

    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { error: `Invalid JSON: ${msg}` };
    }

    const packageName = getPackageName(input.options);
    const usePointers = getUsePointers(input.options);

    let result: ReturnType<typeof generateGoCode>;
    try {
      result = generateGoCode(parsed, packageName, usePointers);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { error: `Code generation failed: ${msg}` };
    }

    const { code, rootType, structCount, propCount } = result;

    return {
      output: {
        value: code,
        type: 'text',
        label: 'Go Structs',
        copyable: true,
        downloadFilename: 'types.go',
        downloadMime: 'text/plain',
      },
      meta: {
        'root type': rootType,
        'structs generated': structCount,
        'top-level properties': propCount,
        'package': packageName,
      },
    };
  },
};
