// Generated by DevToolsHub — https://devtoolshub.dev
import { ToolProcessor, ToolInput, ToolResult } from '@/types/tool';

// ---------------------------------------------------------------------------
// Python style types
// ---------------------------------------------------------------------------

type PythonStyle = 'dataclass' | 'typeddict' | 'dict-literal';

// ---------------------------------------------------------------------------
// Python type inference
// ---------------------------------------------------------------------------

function inferPythonType(value: unknown, nestedClasses: Map<string, string>): string {
  if (value === null) return 'None';
  if (typeof value === 'boolean') return 'bool';
  if (typeof value === 'number') {
    return Number.isInteger(value) ? 'int' : 'float';
  }
  if (typeof value === 'string') return 'str';
  if (Array.isArray(value)) {
    if (value.length === 0) return 'List[Any]';
    // Infer element type from first element
    const elemType = inferPythonType(value[0], nestedClasses);
    return `List[${elemType}]`;
  }
  if (typeof value === 'object') {
    // Nested object — will be represented as Dict[str, Any] unless we generate a class
    return 'Dict[str, Any]';
  }
  return 'Any';
}

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, char) => char.toUpperCase())
    .replace(/^(.)/, (_, char) => char.toUpperCase());
}

function toPythonIdentifier(key: string): string {
  // Replace non-alphanumeric characters with underscores
  let ident = key.replace(/[^a-zA-Z0-9_]/g, '_');
  // Prefix with underscore if starts with a digit
  if (/^[0-9]/.test(ident)) ident = '_' + ident;
  return ident;
}

// ---------------------------------------------------------------------------
// Class/type generation helpers
// ---------------------------------------------------------------------------

interface ClassDef {
  name: string;
  fields: Array<{ pyName: string; origName: string; pyType: string }>;
}

/**
 * Walk the object tree, register nested object classes (depth-first),
 * and return all ClassDef entries in order (deepest first).
 */
function collectClasses(
  obj: Record<string, unknown>,
  className: string,
  registry: ClassDef[],
): void {
  const fields: ClassDef['fields'] = [];

  for (const [key, value] of Object.entries(obj)) {
    const pyName = toPythonIdentifier(key);

    if (
      value !== null &&
      typeof value === 'object' &&
      !Array.isArray(value)
    ) {
      // Nested object — generate a sub-class
      const nestedClassName = toPascalCase(key);
      collectClasses(value as Record<string, unknown>, nestedClassName, registry);
      fields.push({ pyName, origName: key, pyType: nestedClassName });
    } else if (
      Array.isArray(value) &&
      value.length > 0 &&
      value[0] !== null &&
      typeof value[0] === 'object' &&
      !Array.isArray(value[0])
    ) {
      // Array of objects — generate a sub-class for the element type
      const nestedClassName = toPascalCase(key) + 'Item';
      collectClasses(value[0] as Record<string, unknown>, nestedClassName, registry);
      fields.push({ pyName, origName: key, pyType: `List[${nestedClassName}]` });
    } else {
      const nestedClasses = new Map<string, string>();
      const pyType = inferPythonType(value, nestedClasses);
      fields.push({ pyName, origName: key, pyType });
    }
  }

  registry.push({ name: className, fields });
}

// ---------------------------------------------------------------------------
// Code emitters
// ---------------------------------------------------------------------------

function emitDataclasses(classes: ClassDef[]): string {
  const usesListAny = classes.some((c) =>
    c.fields.some((f) => f.pyType.startsWith('List[') || f.pyType === 'Dict[str, Any]' || f.pyType === 'Any' || f.pyType === 'List[Any]')
  );

  const lines: string[] = [];
  lines.push('# Generated by DevToolsHub — https://devtoolshub.dev');
  lines.push('from __future__ import annotations');
  lines.push('from dataclasses import dataclass');

  const typingImports: string[] = [];
  if (usesListAny || classes.some(c => c.fields.some(f => f.pyType.includes('List[')))) {
    typingImports.push('List');
  }
  if (classes.some(c => c.fields.some(f => f.pyType.includes('Dict[')))) {
    typingImports.push('Dict');
  }
  if (classes.some(c => c.fields.some(f => f.pyType === 'Any' || f.pyType === 'List[Any]' || f.pyType === 'Dict[str, Any]'))) {
    typingImports.push('Any');
  }
  if (classes.some(c => c.fields.some(f => f.pyType === 'None'))) {
    typingImports.push('Optional');
  }
  if (typingImports.length > 0) {
    lines.push(`from typing import ${[...new Set(typingImports)].join(', ')}`);
  }
  lines.push('');
  lines.push('');

  for (const cls of classes) {
    lines.push('@dataclass');
    lines.push(`class ${cls.name}:`);
    if (cls.fields.length === 0) {
      lines.push('    pass');
    } else {
      for (const field of cls.fields) {
        const pyType = field.pyType === 'None' ? 'Optional[None]' : field.pyType;
        lines.push(`    ${field.pyName}: ${pyType}`);
      }
    }
    lines.push('');
    lines.push('');
  }

  // Remove trailing blank line
  while (lines.length > 0 && lines[lines.length - 1] === '') lines.pop();

  return lines.join('\n') + '\n';
}

function emitTypedDicts(classes: ClassDef[]): string {
  const lines: string[] = [];
  lines.push('# Generated by DevToolsHub — https://devtoolshub.dev');
  lines.push('from __future__ import annotations');

  const typingImports: string[] = ['TypedDict'];
  if (classes.some(c => c.fields.some(f => f.pyType.includes('List[')))) {
    typingImports.push('List');
  }
  if (classes.some(c => c.fields.some(f => f.pyType.includes('Dict[')))) {
    typingImports.push('Dict');
  }
  if (classes.some(c => c.fields.some(f => f.pyType === 'Any' || f.pyType === 'List[Any]' || f.pyType === 'Dict[str, Any]'))) {
    typingImports.push('Any');
  }
  if (classes.some(c => c.fields.some(f => f.pyType === 'None'))) {
    typingImports.push('Optional');
  }
  lines.push(`from typing import ${[...new Set(typingImports)].join(', ')}`);
  lines.push('');
  lines.push('');

  for (const cls of classes) {
    lines.push(`class ${cls.name}(TypedDict):`);
    if (cls.fields.length === 0) {
      lines.push('    pass');
    } else {
      for (const field of cls.fields) {
        const pyType = field.pyType === 'None' ? 'Optional[None]' : field.pyType;
        lines.push(`    ${field.pyName}: ${pyType}`);
      }
    }
    lines.push('');
    lines.push('');
  }

  while (lines.length > 0 && lines[lines.length - 1] === '') lines.pop();

  return lines.join('\n') + '\n';
}

function jsonValueToPythonLiteral(value: unknown, indent: number): string {
  const pad = ' '.repeat(indent);
  const innerPad = ' '.repeat(indent + 4);

  if (value === null) return 'None';
  if (typeof value === 'boolean') return value ? 'True' : 'False';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'string') {
    // Escape backslashes and single quotes
    const escaped = value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    return `'${escaped}'`;
  }
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value
      .map((item) => innerPad + jsonValueToPythonLiteral(item, indent + 4))
      .join(',\n');
    return `[\n${items},\n${pad}]`;
  }
  if (typeof value === 'object') {
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj);
    if (keys.length === 0) return '{}';
    const entries = keys
      .map((k) => {
        const escapedKey = k.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
        const val = jsonValueToPythonLiteral(obj[k], indent + 4);
        return `${innerPad}'${escapedKey}': ${val}`;
      })
      .join(',\n');
    return `{\n${entries},\n${pad}}`;
  }
  return 'None';
}

function emitDictLiteral(
  parsed: unknown,
  rootType: 'object' | 'array',
): string {
  const lines: string[] = [];
  lines.push('# Generated by DevToolsHub — https://devtoolshub.dev');
  lines.push('');

  if (rootType === 'array') {
    lines.push('data = ' + jsonValueToPythonLiteral(parsed, 0));
  } else {
    lines.push('data = ' + jsonValueToPythonLiteral(parsed, 0));
  }

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Option helpers
// ---------------------------------------------------------------------------

function getStyle(options?: Record<string, unknown>): PythonStyle {
  const s = options?.style;
  if (s === 'typeddict' || s === 'dict-literal') return s;
  return 'dataclass';
}

// ---------------------------------------------------------------------------
// Counting helpers for meta
// ---------------------------------------------------------------------------

function countTopLevelProperties(obj: Record<string, unknown>): number {
  return Object.keys(obj).length;
}

function countNestedTypes(obj: Record<string, unknown>): number {
  let count = 0;
  for (const value of Object.values(obj)) {
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      count += 1 + countNestedTypes(value as Record<string, unknown>);
    } else if (
      Array.isArray(value) &&
      value.length > 0 &&
      value[0] !== null &&
      typeof value[0] === 'object' &&
      !Array.isArray(value[0])
    ) {
      count += 1 + countNestedTypes(value[0] as Record<string, unknown>);
    }
  }
  return count;
}

// ---------------------------------------------------------------------------
// Processor
// ---------------------------------------------------------------------------

const EXAMPLE_INPUT = JSON.stringify(
  {
    id: 1,
    name: 'Alice',
    active: true,
    score: 9.5,
    address: {
      street: '123 Main St',
      city: 'Springfield',
    },
    tags: ['admin', 'editor'],
  },
  null,
  2,
);

export const jsonToPythonProcessor: ToolProcessor = {
  inputLabel: 'JSON Input',
  inputPlaceholder: '{"id":1,"name":"Alice","active":true,"score":9.5,"tags":["admin"]}',
  autoProcess: false,
  exampleInput: EXAMPLE_INPUT,

  optionControls: [
    {
      key: 'style',
      type: 'select',
      label: 'Output Style',
      defaultValue: 'dataclass',
      options: [
        { value: 'dataclass', label: 'dataclass' },
        { value: 'typeddict', label: 'TypedDict' },
        { value: 'dict-literal', label: 'Dict literal' },
      ],
    },
  ],

  process(input: ToolInput): ToolResult {
    const raw = input.value.trim();
    if (!raw) return { error: 'Paste a JSON object or array to convert.' };

    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { error: `Invalid JSON: ${msg}` };
    }

    if (parsed === null) {
      return { error: 'Input is null — paste a JSON object or array.' };
    }

    const rootIsArray = Array.isArray(parsed);
    const rootType: 'object' | 'array' = rootIsArray ? 'array' : 'object';

    const style = getStyle(input.options);

    // For dict-literal style, we don't need class generation
    if (style === 'dict-literal') {
      const code = emitDictLiteral(parsed, rootType);

      const topProps = rootIsArray
        ? (parsed as unknown[]).length
        : countTopLevelProperties(parsed as Record<string, unknown>);

      return {
        output: {
          value: code,
          type: 'text',
          label: 'Python dict literal',
          copyable: true,
          downloadFilename: 'data.py',
          downloadMime: 'text/x-python',
        },
        meta: {
          'root type': rootType,
          'top-level properties': topProps,
          'nested types': 0,
        },
      };
    }

    // dataclass / TypedDict — root must be an object (or array of objects)
    let rootObj: Record<string, unknown>;

    if (rootIsArray) {
      const arr = parsed as unknown[];
      if (arr.length === 0) {
        return { error: 'The JSON array is empty — cannot infer types.' };
      }
      const first = arr[0];
      if (first === null || typeof first !== 'object' || Array.isArray(first)) {
        return { error: 'For dataclass/TypedDict generation, the array must contain objects.' };
      }
      rootObj = first as Record<string, unknown>;
    } else if (typeof parsed === 'object') {
      rootObj = parsed as Record<string, unknown>;
    } else {
      return { error: 'Input must be a JSON object or array of objects for dataclass/TypedDict generation.' };
    }

    const classes: ClassDef[] = [];
    collectClasses(rootObj, 'RootObject', classes);

    const code =
      style === 'typeddict' ? emitTypedDicts(classes) : emitDataclasses(classes);

    const topProps = countTopLevelProperties(rootObj);
    const nestedCount = countNestedTypes(rootObj);

    return {
      output: {
        value: code,
        type: 'text',
        label: `Python ${style === 'typeddict' ? 'TypedDict' : 'dataclass'} models`,
        copyable: true,
        downloadFilename: 'models.py',
        downloadMime: 'text/x-python',
      },
      meta: {
        'root type': rootType,
        'properties found': topProps,
        'nested types': nestedCount,
      },
    };
  },
};
